### ISSUE TITLE
☄ Epic: UI Issues

### ISSUE THREAD

**Issue by laritakr** [notch8/palni_palci_knapsack#170]
# Story

UI should be compared to https://demo.hykucommons.org/ and issues not appearing there will be given a lower priority. 

# Acceptance Criteria

Resolve the following tickets:

- [x] #172
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/142
- [x] #173
- [x] #174
- [x] #177
- [x] #175
- [x] #176
- [x] #171
- [x] #178
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/156
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/166
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/157
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/40
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/153
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/147
- [ ] Collection show page masonry view (pre-existing issue in production so no ticket created yet)
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/73
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/71
- [x] https://github.com/scientist-softserv/palni_palci_knapsack/issues/48

There may be some relevant tickets here as well: https://github.com/scientist-softserv/palni_palci_knapsack/issues/33

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

UI issues are documented [here.](https://docs.google.com/document/d/1K7aJcaqtsUa60Uq9c-f0gONF1d6BI_i_I3LSdY_m89k/edit?tab=t.0)
