### ISSUE TITLE
Implement Batch Email Notifications

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/palni_palci_knapsack#435]
# Summary

[SOW](https://docs.google.com/document/d/1YthZ9Jhh5Tfmap73BgpN5IAmcVk95aSHbNNludpVXYg/edit)

The goal is to implement batch email notifications for some activities/trigers in the Hyku application. The notifications should match those of the One-step mediated deposit workflow. That includes:
- Notifications to submitter and approver for activity related to mediated deposit, which currently produce notifications within the app but not pushed out to email.  These including:
  - Work submitted awaiting review
  - Work reviewed and accepted
  - Work reviewed and sent back with comment
  - Work revised and resubmitted for review

## Acceptance Criteria
- [ ] Email notifications to submitter and approver for activity related to mediated deposit are set up and include: ([see below](https://github.com/scientist-softserv/palni-palci/issues/1005#issuecomment-2052160513))
  - [ ] Work submitted awaiting review
  - [ ] Work reviewed and accepted
  - [ ] Work reviewed and sent back with comment
  - [ ] Work revised and resubmitted for review
- [ ] Email notifications to authors related to views and downloads of their works are set up
- [ ] Emails should not be sent if the user has already read them from the notifications dashboard

### TASKS

- [x] notch8/palni-palci#1022
- [x] notch8/palni-palci#1023

## Testing Instructions

1. Be sure the tenant has a contact email set on the account settings, and one-step mediated deposit set for the admin set. (This requires approval for every work created, for example, which also triggers the notifications).
2. Go to User profile to set the batch email notification frequency.
3. Create a work. Notice the notification bell should have an additional alert. This alert should be what gets emailed to the user email, per the selected frequency.

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/7ef52c17-1b7e-407a-a1b2-67822a2573ea)

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/e05a39ad-f0cc-42d1-b3b3-43fce0f2fc0e)

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/827c7fe8-3972-43a3-8623-aec5a87c0c52)

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/2e732a6a-9cce-4515-a659-003963d4ca77)

## Notes

Spike results: https://github.com/scientist-softserv/palni-palci/issues/1005#issuecomment-2073611653
Implementation brainstorm: https://github.com/scientist-softserv/palni-palci/issues/1005#issuecomment-2078113101
